### ISSUE TITLE
c and f are the convolution and fully connected layers. What is the function of s?

### ISSUE THREAD

**Issue by trinity97** [catchchaos/CUDA-CNN#1]
See, I know it works but I've no idea how!!

**Comment by sedflix** [comment]
me too!!

**Comment by paramhanji** [comment]
If you can point out which part of the code is unclear, I can perhaps help you out. A generic title like this isn't too helpful.

**Comment by trinity97** [comment]
Sorry for the kinda unhelpful title. I want to change the way layers are organized and make it a network with 3 fully connected layers instead. What changes would you suggest?

**Comment by paramhanji** [comment]
You will have to change the way forward and backward propagation are implemented - functions `forward_pass()` and `back_pass()` in main.cu

**Comment by paramhanji** [comment]
Also s stands for the step function (see [definition](https://github.com/catchchaos/CUDA-CNN/blob/master/layer.cu#L80)). This is the activation function applied after the convolution operation.

**Comment by dhy2000** [comment]
Thanks to reply, but I'm still confused, so I tried to describe the question more clear in new issue: #3
